title: "Bitcoin: a Work in Progress"
subtitle: "Technical innovations from the trenches. Based on the podcast Bitcoin, Explained"
author: Sjors Provoost
language: en-US
include-before:
  - '`\newpage{}`{=latex}'
