title: "Bitcoin: a Work in Progress"
subtitle: "Lorum Ipsum technical innovations from the trenches"
author: Sjors Provoost
language: en-US
titlepage: true
output:
    pdf_document
include-before:
  - '`\newpage{}`{=latex}'
